# Generated by Django 3.2.10 on 2023-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='commande',
            name='transitionClient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
