# Generated by Django 3.2.10 on 2023-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_remove_utilisateur_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='name',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='addresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profil',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
