# Generated by Django 3.2.10 on 2023-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20231123_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='cni',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
