# Generated by Django 3.2.10 on 2023-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_utilisateur_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='cni',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
