# Generated by Django 3.2.10 on 2023-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='dimensions',
            field=models.CharField(default='dim', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images/image.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='support',
            field=models.CharField(default='support', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='titre', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='tools',
            field=models.CharField(default='tools', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
