# Generated by Django 3.2.10 on 2023-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, default='Numerique', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='dimensions',
            field=models.CharField(default='10x10', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='support',
            field=models.CharField(default='toile', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
